 name: sync to gitee
#Due to incomplete environment development, CI build is disabled.
 #on: [push]
 on: []
 jobs:
   deploy:
     runs-on: ubuntu-latest
     if: github.repository_owner == 'qilingframework'
     steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - uses: xwings/sync-repo-action@master
       with:
         run: git config --global --add safe.directory *
         ssh_private_key: ${{ secrets.GITEE_KEY }}
         target_repo: ssh://git@gitee.com/qilingframework/qiling.git
         
